server:
  port: 8086

spring:
  application:
    name: Config-Default

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Nneeraj24/microservice-tutorial-config
          clone-on-start: true
          default-label: main
